version: "2.1"
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet:  10.110.0.0/24
volumes:
  ssl_data:
services:
  db:
    image: postgres:12
    volumes:
      - ${ACME_PREFIX}/db_data:/var/lib/postgresql/data
      - ${ACME_PREFIX}/etc/postgres:/docker-entrypoint-initdb.d
    restart: always
    environment:
      POSTGRES_PASSWORD: ${ACME_SUPERUSER_PW}
      POSTGRES_DB: default # Database 'acme' is created by the init.sh script
      POSTGRES_USER: acme
      ACME_ADMIN_PW: ${ACME_ADMIN_PW}
      ACME_RW_PW: ${ACME_RW_PW}
      ACME_RO_PW: ${ACME_RO_PW}
  reverse_proxy:
    image: acme/reverse_proxy:latest
    restart: always
    ports:
      - "443:443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ssl_data:/etc/resty-auto-ssl
      - ${ACME_PREFIX}/etc/openresty/nginx.conf:/etc/openresty/nginx.conf
      - ${ACME_PREFIX}/etc/openresty/conf.d:/etc/openresty/conf.d
      - ${ACME_PREFIX}/etc/openresty/trusted_roots.pem:/etc/ssl/trusted_roots.pem:ro
      - ${ACME_PREFIX}/etc/resty-auto-ssl/resty_auto_ssl.sh:/etc/resty-auto-ssl/letsencrypt/conf.d/resty_auto_ssl.sh
  app:
    image: acme/app:latest
    restart: always
    depends_on:
      - db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - .:/app
      - ${ACME_PREFIX}/etc/acme_server:/etc/acme_server
      - ${ACME_PREFIX}/log:/var/log/supervisor
      - ${ACME_PREFIX}/etc/supervisor/conf.d:/etc/supervisor/conf.d
    environment:
      APP_CONFIG_FILE: ${ACME_CONFIG_FILE}
